config/routes.rb
Rails.application.routes.draw do
  root 'index#index'
  get '/results/:id' => 'index#show', as: :results

  require 'sidekiq/web'

  namespace :api, defaults: { format: :json } do
    post '/tokenize', to: 'tokenizer#tokenize'
  end

  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord
end

app/controllers/api/tokenizer_controller.rb
module Api
  class TokenizerController < ApplicationController
    wrap_parameters :token

    def tokenize
      $REDIS ||= Redis.new(url: ENV["REDISCLOUD_URL"] || 'redis://localhost:6379/14')
      # Send individual aspects for review
      AspectDetectionWorker.perform_async(token_params[:review], token_params[:movie_id], token_params[:user_id])
      render :json => {:message => "received"}, :status => 200
    end

    private

    def token_params
      params.require(:token).permit(:review, :movie_id, :user_id)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  before_action :conn_to_redis
  after_action :close_redis_conn
  def index
    @results = @redis.keys.select { |e| !e.include?"_" }
  end

  def show
    @id = params[:id]
    @results = {}

    keys = @redis.keys
    keys.each do |key|
      next if !key.include? "_"
      @results[@id.to_sym] ||= {}
      case key
      when "rv_#{@id}" then @results[@id.to_sym][:review] = @redis.get key
      when "sa_rv_#{@id}" then @results[@id.to_sym][:sa_rv] = JSON.parse(@redis.get key)
      when "sg_#{@id}"
        sg = JSON.parse(@redis.get key)
        @results[@id.to_sym][:sg] = sg.to_json
        aspect_sentiments = {}
        sg.each do |k, v|
          aspect_sentiments[k] = JSON.parse(@redis.hget "sa_sg_#{@id}", k.to_s)
        end
        @results[@id.to_sym][:asp_s] = aspect_sentiments.to_json
      end
    end
  end

  private

  def conn_to_redis
    @redis = Redis.new(url: ENV["REDISCLOUD_URL"] || 'redis://localhost:6379/14')
  end

  def close_redis_conn
    @redis.close
  end
end

app/views/index/index.html.erb
<h2>Welcome to Minerva.</h2>
<div id="center">
  <% @results.each do |element| %>
    <p><%= element %></p>
    <p><%= link_to 'Show', results_path(element) %></p>
  <% end %>
</div>

app/views/index/show.html.erb
<%= content_for :head do %>
  <style>

	.node {
		cursor: pointer;
	}

	.node circle {
	  fill: #fff;
	  stroke: steelblue;
	  stroke-width: 3px;
	}

	.node text {
	  font: 12px sans-serif;
	}

	.link {
	  fill: none;
	  stroke: #ccc;
	  stroke-width: 2px;
	}

  </style>


  <!-- load the d3.js library -->
  <script src="http://d3js.org/d3.v3.min.js"></script>
  <!-- Plotly.js -->
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
<% end %>

<h1>Movie Details:</h1>
<div class="center">
<% @results.each do |key, value| %>
  <p> Movie id: <%= key %> </p>
  <p> Review: <%= value[:review] %> </p>
  <p> Sentiment of full Review: <%= value[:sa_rv] %> </p>
  <p> Sentiment Groups: <p id="sg"><%= value[:sg] %></p> </p>
  <p> Aspect Based sentiments: <p id="asp_s"><%= value[:asp_s] %></p></p>
<% end %>
<%= link_to "Back", :root %>
</div>

<div id="myDiv">
  <!-- Plotly chat drawn here -->
</div>

<script type="text/javascript">
  var sentiments = JSON.parse($('#asp_s').text());
  var score = [];
  var concepts = Object.keys(sentiments);
  for (var i = 0; i < concepts.length; i++) {
      score[i] = sentiments[concepts[i]].score;
  };
  console.log("Score:" + score);
  console.log("Concepts:" + concepts);

  var trace1 = {
    x: concepts,
    y: score,
    type: 'bar',
    text: concepts
  };

  var data = [trace1];

  var layout = {
    title: 'Aspect level sentiment score' ,
    font:{
      family: 'Raleway, snas-serif'
    },
    showlegend: false,
    xaxis: {
      tickangle: -45
    },
    yaxis: {
      zeroline: false,
      gridwidth: 2
    },
    bargap :0.05
  };

  Plotly.newPlot('myDiv', data, layout);

  var sent_groups = JSON.parse($('#sg').text());
  opinions = [];
  sentences = [];
  children = [];

  for (var i = 0; i < concepts.length; i++) {
    opinions[i] = sent_groups[concepts[i]].opinions;
    sentences[i] = sent_groups[concepts[i]].sentences;
    child = {
      "name": concepts[i],
      "parent": "Movie",
      "children": [
        {
          "name": "opinion: " + opinions[i],
          "parent": concepts[i]
        },
        {
          "name": "sentence: " + sentences[i],
          "parent": concepts[i]
        }
      ]
    };
    children.push(child);
  };

  var treeData = [
  {
    "name": "Movie",
    "parent": "null",
    "children": children
  }
];


// ************** Generate the tree diagram	 *****************
var margin = {top: 20, right: 120, bottom: 20, left: 120},
	width = 960 - margin.right - margin.left,
	height = 1000 - margin.top - margin.bottom;

var i = 0,
	duration = 750,
	root;

var tree = d3.layout.tree()
	.size([height, width]);

var diagonal = d3.svg.diagonal()
	.projection(function(d) { return [d.y, d.x]; });

var svg = d3.select("body").append("svg")
	.attr("width", width + margin.right + margin.left)
	.attr("height", height + margin.top + margin.bottom)
  .append("g")
	.attr("transform", "translate(" + margin.left + "," + margin.top + ")");

root = treeData[0];
root.x0 = height / 2;
root.y0 = 0;

update(root);

d3.select(self.frameElement).style("height", "500px");

function update(source) {

  // Compute the new tree layout.
  var nodes = tree.nodes(root).reverse(),
	  links = tree.links(nodes);

  // Normalize for fixed-depth.
  nodes.forEach(function(d) { d.y = d.depth * 180; });

  // Update the nodes…
  var node = svg.selectAll("g.node")
	  .data(nodes, function(d) { return d.id || (d.id = ++i); });

  // Enter any new nodes at the parent's previous position.
  var nodeEnter = node.enter().append("g")
	  .attr("class", "node")
	  .attr("transform", function(d) { return "translate(" + source.y0 + "," + source.x0 + ")"; })
	  .on("click", click);

  nodeEnter.append("circle")
	  .attr("r", 1e-6)
	  .style("fill", function(d) { return d._children ? "lightsteelblue" : "#fff"; });

  nodeEnter.append("text")
	  .attr("x", function(d) { return d.children || d._children ? -13 : 13; })
	  .attr("dy", ".35em")
	  .attr("text-anchor", function(d) { return d.children || d._children ? "end" : "start"; })
	  .text(function(d) { return d.name; })
	  .style("fill-opacity", 1e-6);

  // Transition nodes to their new position.
  var nodeUpdate = node.transition()
	  .duration(duration)
	  .attr("transform", function(d) { return "translate(" + d.y + "," + d.x + ")"; });

  nodeUpdate.select("circle")
	  .attr("r", 10)
	  .style("fill", function(d) { return d._children ? "lightsteelblue" : "#fff"; });

  nodeUpdate.select("text")
	  .style("fill-opacity", 1);

  // Transition exiting nodes to the parent's new position.
  var nodeExit = node.exit().transition()
	  .duration(duration)
	  .attr("transform", function(d) { return "translate(" + source.y + "," + source.x + ")"; })
	  .remove();

  nodeExit.select("circle")
	  .attr("r", 1e-6);

  nodeExit.select("text")
	  .style("fill-opacity", 1e-6);

  // Update the links…
  var link = svg.selectAll("path.link")
	  .data(links, function(d) { return d.target.id; });

  // Enter any new links at the parent's previous position.
  link.enter().insert("path", "g")
	  .attr("class", "link")
	  .attr("d", function(d) {
		var o = {x: source.x0, y: source.y0};
		return diagonal({source: o, target: o});
	  });

  // Transition links to their new position.
  link.transition()
	  .duration(duration)
	  .attr("d", diagonal);

  // Transition exiting nodes to the parent's new position.
  link.exit().transition()
	  .duration(duration)
	  .attr("d", function(d) {
		var o = {x: source.x, y: source.y};
		return diagonal({source: o, target: o});
	  })
	  .remove();

  // Stash the old positions for transition.
  nodes.forEach(function(d) {
	d.x0 = d.x;
	d.y0 = d.y;
  });
}

// Toggle children on click.
function click(d) {
  if (d.children) {
	d._children = d.children;
	d.children = null;
  } else {
	d.children = d._children;
	d._children = null;
  }
  update(d);
}
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minerva</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :head %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>